# Generated by Django 4.2 on 2025-10-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product1_image', models.ImageField(upload_to='product/')),
                ('product1_video', models.FileField(upload_to='product/')),
                ('product2_image', models.ImageField(upload_to='product/')),
                ('product2_video', models.FileField(upload_to='product/')),
                ('product3_image', models.ImageField(upload_to='product/')),
                ('product3_video', models.FileField(upload_to='product/')),
            ],
        ),
        migrations.RenameField(
            model_name='product_details',
            old_name='image1',
            new_name='rum',
        ),
        migrations.RenameField(
            model_name='product_details',
            old_name='image2',
            new_name='rum50',
        ),
        migrations.RenameField(
            model_name='product_details',
            old_name='image3',
            new_name='vodka',
        ),
        migrations.AddField(
            model_name='product_details',
            name='whisky',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
