# Generated by Django 4.2 on 2025-10-15 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_about_rename_image1_product_details_rum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_details',
            options={'verbose_name': 'Product Detail', 'verbose_name_plural': 'Product Details'},
        ),
        migrations.RenameField(
            model_name='product_details',
            old_name='rum',
            new_name='rum70',
        ),
    ]
